language: cpp
sudo: required
dist: xenial

os:
   - linux
   - osx

compiler:
   - gcc
   - clang

addons:
   apt:      
      packages:
         - cmake
         - doxygen
         - libgcrypt-dev
         - pkg-config
         - libjsoncpp1
         - libjsoncpp-dev

before_script:
   - if [[ $TRAVIS_OS_NAME == "osx" ]]; then brew update && brew install pkg-config jsoncpp doxygen curl && brew upgrade cmake libgcrypt; fi

script:
   - cmake . -DCMAKE_BUILD_TYPE="Release" -DCMAKE_CXX_FLAGS="-Wall -Wextra -O2 -finline-functions"
   - make -j3

before_deploy:
   - make docs
   - rm -rfv "*.cmake CMakeFiles CMakeCache.txt Makefile lib 
        src scripts include README.md .travis.yml 
        .gitignore Doxyfile CMakeLists.txt"
   - rm -r docs/latex
   - mv docs/html/* .

deploy:
   provider: pages
   skip_cleanup: true
   github_token: $GITHUB_TOKEN
   on:
       condition: "$CC = gcc && $TRAVIS_OS_NAME = linux"
