language: cpp
sudo: required
dist: xenial

os:
   - linux
   - osx

compiler:
   - gcc
   - clang

addons:
   apt:      
      packages:
         - cmake
         - doxygen
         - libgcrypt-dev
         - pkg-config

before_script:
   - if [[ $TRAVIS_OS_NAME == "linux" ]]; then sudo add-apt-repository ppa:deadsnakes/ppa -y; fi
   - if [[ $TRAVIS_OS_NAME == "linux" ]]; then sudo add-apt-repository ppa:mstipicevic/ninja-build-1-7-2 -y; fi
   - if [[ $TRAVIS_OS_NAME == "linux" ]]; then sudo apt update; fi
   - if [[ $TRAVIS_OS_NAME == "linux" ]]; then sudo apt install -y python3.6 ninja-build; fi
   - if [[ $TRAVIS_OS_NAME == "linux" ]]; then curl https://bootstrap.pypa.io/get-pip.py | sudo python3.6; fi
   - if [[ $TRAVIS_OS_NAME == "linux" ]]; then sudo python3.6 -m pip install meson; fi
   - if [[ $TRAVIS_OS_NAME == "linux" ]]; then bash scripts/jsoncpp.sh; fi
   - if [[ $TRAVIS_OS_NAME == "osx" ]]; then brew update && brew install pkg-config jsoncpp doxygen curl && brew upgrade cmake libgcrypt; fi

script:
   - cmake . -DCMAKE_BUILD_TYPE="Release" -DCMAKE_CXX_FLAGS="-Wall -Wextra -O2 -finline-functions"
   - make -j3

before_deploy:
   - make docs
   - rm -rfv "*.cmake CMakeFiles CMakeCache.txt Makefile lib 
        src scripts include README.md .travis.yml 
        .gitignore Doxyfile CMakeLists.txt"
   - rm -r docs/latex
   - mv docs/html/* .

deploy:
   provider: pages
   skip_cleanup: true
   github_token: $GITHUB_TOKEN
   on:
       condition: "$CC = gcc && $TRAVIS_OS_NAME = linux"
